export function renderOnboarding(): string[] {
  return [
    "Welcome to nexussy. One CLI, two speeds: ask for help or launch the build pipeline.",
    "",
    "First-time setup:",
    "  ./nexussy.sh cli --setup          choose provider, hidden API key, model",
    "  ./nexussy.sh doctor               check provider, Pi worker, ports, config",
    "",
    "What it can do:",
    "  ● Interview  clarify requirements and complexity",
    "  ● Design     draft architecture, dependencies, risks, test strategy",
    "  ● Validate   check the design and request corrections",
    "  ● Plan       write devplan, handoff, and phase files",
    "  ● Review     review the plan before implementation",
    "  ● Develop    spawn workers, use worktrees, merge changes, report results",
    "",
    "How to use it:",
    "  Ask normal questions to shape the idea without starting work",
    "  Type a build request and confirm when nexussy offers to run it",
    "  Or start deliberately with a slash command:",
    "  /new Create a FastAPI todo app with SQLite and tests",
    "",
    "Useful commands:",
    "  /new <description>   start a pipeline run",
    "  /status              show compact run status",
    "  /plan                show planning artifacts",
    "  /workers             inspect worker activity",
    "  /dashboard           open the monitoring dashboard",
    "  /help                show all commands",
  ];
}
